### ISSUE TITLE
Update documentation for `PREFECT_API_URL` 

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect-helm#109]
Related to https://github.com/PrefectHQ/prefect-helm/issues/108 and other community messages, the documentation is not clear on what users should set the value of `PREFECT_API_URL` to.

**Comment by madkinsz** [comment]
Might also be worth using `PREFECT_ORION_UI_API_URL` for clarity where relevant.

**Comment by jamiezieziula** [comment]
Values file - https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-orion/values.yaml#L36

**Comment by jamiezieziula** [comment]
Orion API url values file - https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-agent/values.yaml#L69
