### ISSUE TITLE
Sidecar container option for helm chart

### ISSUE THREAD

**Issue by ftasbasi** [PrefectHQ/prefect-helm#122]
Are we able to add sidecar to agent or server deployments from helm chart? I couldn't see any option like that?

**Comment by jawnsy** [comment]
Hey, thanks for your report! It isn't possible right now, but we could add it (or review a pull request if you'd like to contribute one). I think an `extraContainers` option with additional sidecars would make sense.

Also, if you don't mind sharing, it would be interesting for us to learn more about your intended usage for these sidecar containers

**Comment by ftasbasi** [comment]
@jawnsy 
I'm planning to run a vpn sidecar container in prefect pod.
Where should I find guidance about extraContainers?
I couldn't find in this repo.
Thanks in advance.

**Comment by rbastian** [comment]
@jawnsy If I may butt in here, the sidecar container option could be used to pull secrets from an external secret store like Hashicorp Vault.

**Comment by ftasbasi** [comment]
@jawnsy my purpose was to use tailscale sidecar
