### ISSUE TITLE
replace soon-to-be deprecated set-output syntax in GHA

### ISSUE THREAD

**Issue by parkedwards** [PrefectHQ/prefect-helm#125]
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/

5/31/23 is the cutoff

**Comment by madkinsz** [comment]
😬 Can ya'll take this in PrefectHQ/prefect too?

**Comment by parkedwards** [comment]
https://github.com/search?q=org%3APrefectHQ+%22%3A%3Aset-output%22&type=code

**Comment by parkedwards** [comment]
there are some support repos i've skipped, as i dont have access / they dont run GHA workflows at all.  we can revisit if we need to update those
