### ISSUE TITLE
When attempting to use this chart to deploy I receive an error showing the cloud api URL being a mash of duplicated account and workspace paths

### ISSUE THREAD

**Issue by k-walsh-gmg** [PrefectHQ/prefect-helm#126]
When attempting to deploy a prefect agent there is no secret created. When I did manually create the secret for the cloud it wasn't decoded by the deployment.

**Comment by k-walsh-gmg** [comment]
From the pod logs(those WORKSPACE_ID and ACCOUNT_ID have my actual values in them):
prefect.exceptions.PrefectHTTPStatusError: Client error '404 Not Found' for url 'https://api.prefect.cloud/api/accounts/{ACCOUNT_ID}/workspaces/{WORKSPACE_ID}/accounts/{ACCOUNT_ID}/workspaces/{WORKSPACE_ID}/flow_runs/filter'

**Comment by jamiezieziula** [comment]
Hi @k-walsh-gmg -
> When attempting to deploy a prefect agent there is no secret created. When I did manually create the secret for the cloud it wasn't decoded by the deployment.

That's correct, the chart will not create a secret for you - you will need to specify the name of an existing k8s secret to reference

> When attempting to use this chart to deploy I receive an error showing the cloud api URL being a mash of duplicated account and workspace paths
Can you share your values.yaml config block for the cloud configuration, with account is and workspace id obfuscated?

**Comment by jamiezieziula** [comment]
[this](https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-agent/templates/_helpers.tpl#L18) is where the URL configuration is created
