### ISSUE TITLE
Prefect server should have liveness and readyness probe

### ISSUE THREAD

**Issue by davzucky** [PrefectHQ/prefect-helm#132]
As a DevOps team relying on Kubernetes to give us the health of the system, we need to have Prefect to provide us with the status of the pod using the [liveness and readiness probe](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/)

At the moment, the Prefect server is missing endpoints like 
- ping => used for liveness
- health => used for readiness

I'm also raising an issue on the Prefect repository to get these endpoints added.

**Comment by jimid27** [comment]
Depends: https://github.com/PrefectHQ/prefect/issues/8940
