### ISSUE TITLE
Allow users to configure structured logging

### ISSUE THREAD

**Issue by jawnsy** [PrefectHQ/prefect-helm#188]
For humans checking logs via `kubectl logs`, human-readable logs (as we have now) are preferable.

However, in cloud environments (e.g. for production installations), using structured logging (JSON) is often preferable, because they are easier to search. Log messages may also form the basis of alerting.

We should continue with our current default, but allow users to explicitly opt-in to JSON logs. This would be useful for our internal workers/agents as well.

Related issue: https://github.com/PrefectHQ/prefect/issues/9197

**Comment by meggers** [comment]
This would be valuable to us

**Comment by ismailhammounou** [comment]
Same here.  +1

**Comment by jamiezieziula** [comment]
closing in response to this [issue](https://github.com/PrefectHQ/prefect/issues/9197) being closed
