### ISSUE TITLE
Support `match` argument for Prefect Agent

### ISSUE THREAD

**Issue by OptimeeringBigya** [PrefectHQ/prefect-helm#195]
Agents supports dynamically matching work queue names with the specified prefix for the agent to pull from using the `match` argument. This cannot be performed using the values for the helm chart.

**Comment by jamiezieziula** [comment]
Hi @OptimeeringBigya - we would welcome a PR to add this as a configuration option. ICYMI - [workers](https://docs.prefect.io/2.11.3/concepts/work-pools/) have been promoted to GA and are now the recommended approach for scheduling work.
