### ISSUE TITLE
Prefect worker always tries to pull an image `prefecthq/prefect:2.11.1-python3.11-kubernetes` which does not exist.

### ISSUE THREAD

**Issue by Hongbo-Miao** [PrefectHQ/prefect-helm#217]
I am trying to use `2.11.0-python3.11-kubernetes` (not `2.11.1-python3.11-kubernetes`) for Prefect worker by:

```shell
helm upgrade \
  prefect-worker \
  prefect-worker \
  --install \
  --repo=https://prefecthq.github.io/prefect-helm \
  --namespace=hm-prefect \
  --create-namespace \
  --values=my-values.yaml
```

**my-values.yaml**:

```shell
agent:
  image:
    repository: docker.io/prefecthq/prefect
    prefectTag: 2.11.0-python3.11-kubernetes
  apiConfig: server
  config:
    workPool: hm-kubernetes-pool
  serverApiConfig:
    apiUrl: http://prefect-server.hm-prefect.svc:4200/api
```

However, this gives error

```shell
Failed to pull image "prefecthq/prefect:2.11.1-python3.11-kubernetes": rpc error: code = NotFound desc = failed to pull and unpack image "docker.io/prefecthq/prefect:2.11.1-python3.11-kubernetes": failed to resolve reference "docker.io/prefecthq/prefect:2.11.1-python3.11-kubernetes": docker.io/prefecthq/prefect:2.11.1-python3.11-kubernetes: not found
```

Instead of `2.11.0-python3.11-kubernetes`, it always tries to pull `prefecthq/prefect:2.11.1-python3.11-kubernetes` which does not exist as of today.

And I tired other version for `prefectTag` field, and same. It seems this `prefectTag` is being ignored.

On the other side, Prefect Server and Prefect Agent can install the right version.

Any ideas? Thanks!

**Comment by parkedwards** [comment]
hey @Hongbo-Miao - just making sure, is your worker's `values.yaml` nested in a `worker` key, and not `agent`?

https://github.com/PrefectHQ/prefect-helm/blob/main/charts/prefect-worker/values.yaml#L14

**Comment by Hongbo-Miao** [comment]
Thanks @parkedwards ! You are right, I copied from my old agent config.
It should be `worker:` instead of `agent:` in **my-values.yaml** file.
Now it works well! 😃
