### ISSUE TITLE
Update disabling postgresql  

### ISSUE THREAD

**Issue by allemp** [PrefectHQ/prefect-helm#240]
Currently the values.yaml says enable: false to disable but the correct way (as in the readme) is useSubChart: false

**Comment by jamiezieziula** [comment]
Hi @allemp - Actually both values are neccessary.

This value:
```
postgresql:
  enabled: true
```
signifies where the Prefect server should expect to use postgres configuration values. If the value is set to `false`, the server will then default to using `sqlite`

Whereas this value:
```
postgresql:
  ...
  useSubChart: false
```
defines whether or not the sub chart of postgresql should be used. If set to `false` the user is expected to provide an external postgresql connection under `externalHostname`.
