### ISSUE TITLE
publicApiUrl name change ?

### ISSUE THREAD

**Issue by brks-rssll** [PrefectHQ/prefect-helm#261]
The prefect-server README still mentions publicApiUrl but if you still use that it errors out at as values.schema.json doesn't have it.

Presumably we need to use prefectApiUrl instead?

**Comment by jamiezieziula** [comment]
Hi @brks-rssll - we [released](https://github.com/PrefectHQ/prefect-helm/releases/tag/2023.10.17) a breaking change yesterday. Can you share where you're still seeing the reference to publicApiUrl parameter?

**Comment by jamiezieziula** [comment]
I see where it is in the readme. I'll update this now!
