### ISSUE TITLE
prometheus-prefect-exporter helm chart

### ISSUE THREAD

**Issue by ialejandro** [PrefectHQ/prefect-helm#263]
HI,

I'm using Prefect Platform everyday for our ML Engineers. First of all, thanks for spend time on improve Prefect and maintain helm charts.

In our case, we monitoring Prefect with Prometheus and visualizate metrics with Grafana, so we develop a simple exporter written in Python (currently migrate to Golang), but for now, works properly and provide us enough metrics to generate alerts if some flow-run failed, all deployments are paused, if work queues or work pools aren't available...

So, here are the repositories:

* prometheus-prefect-exporter: <https://github.com/devops-ia/prometheus-prefect-exporter> (written in Python) but I'm working to rewrite on Golang. Here's Docker releases: [docker releases](https://hub.docker.com/repository/docker/devopsiaci/prometheus-prefect-exporter/general)
* helm chart prometheus-prefect-exporter: <https://github.com/devops-ia/helm-charts/tree/main/charts/prometheus-prefect-exporter>
* dashboards: [prefect-platform-overview](https://grafana.com/grafana/dashboards/19806-prefect-platform-overview/) | [prefect-platform-flow-run-overview](https://grafana.com/grafana/dashboards/19809-prefect-flow-runs-overview/)

If you want, I can transferring a repository and open new PR on your new transfered repository. So, that's all... if you want speak or next-steps, I will be waiting. Thank you very much for everything.

**Comment by ialejandro** [comment]
yes @jimid27, my proposal:

* transfer repo prometheus-prefect-exporter to PrefectHQ org. I can do it now.
* create your own helm-chart repo and move only code chart from my repo (because I'm using same repository for differents chats I'm not isolated charts per project). If you want I can open a PR with all code when you've the repository created.

When you confirm I'll start the transfer and wait until you create helm-chart repository.

Thx!

**Comment by jimid27** [comment]
This plan works for me!

**Comment by ialejandro** [comment]
@jimid27 i couldn't transfer repo because i haven't permissions to create on your repo (is normal i've already read github's docs). So, you should fork prometheus-prefect-exporter repo on your org. Sorry :(

**Comment by jimid27** [comment]
Hey @ialejandro! Would it be possible for you to give my GH user (@jimid27) permission to the [repo](https://github.com/devops-ia/prometheus-prefect-exporter) so I can initiate the transfer?  I should have those required permissions.  
Also if you would like to DM about this I am available on the [Prefect Community Slack](https://communityinviter.com/apps/prefect-community/prefect-community)! (Jimi Dodd-o)
