### ISSUE TITLE
PREFECT_UI_SERVE_BASE should be runtime configurable

### ISSUE THREAD

**Issue by ddl-ebrown** [PrefectHQ/prefect-helm#270]
I'm trying to configure Prefect behind a Kubernetes ingress that is shared for multiple applications. Therefore I want to run it under the `/prefect` path to isolate it from other services. The Helm chart seemingly supports this, but it would appear Prefect itself does not.

I've configured the ingress properly and requests are routed to the prefect service in the cluster. However, the HTML that's served is not using relative paths, so loading the UI breaks. Here's the relevant HTML

```html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <link rel="apple-touch-icon" sizes="180x180" href="/ico/apple-touch-icon.png">
    
   
    
    <link rel="icon" id="favicon-32" type="image/png" sizes="32x32" href="/ico/favicon-32x32.png" media="(prefers-color-scheme:light)">
    <link rel="icon" id="favicon-16" type="image/png" sizes="16x16" href="/ico/favicon-16x16.png" media="(prefers-color-scheme:light)">

    <link rel="icon" id="favicon-32-dark" type="image/png" sizes="32x32" href="/ico/favicon-32x32-dark.png" media="(prefers-color-scheme:dark)">
    <link rel="icon" id="favicon-16-dark" type="image/png" sizes="16x16" href="/ico/favicon-16x16-dark.png" media="(prefers-color-scheme:dark)">
    
    <link rel="icon" href="/favicon.ico" media="(prefers-color-scheme:no-preference)">
    <link rel="icon" href="/favicon.ico" media="(prefers-color-scheme:light)">
    <link rel="icon" href="/favicon-dark.ico" media="(prefers-color-scheme:dark)">

    <link rel="manifest" href="/ico/site.webmanifest">
    <link rel="mask-icon" href="/ico/safari-pinned-tab.svg" color="#5bbad5">
    
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="theme-color" content="#ffffff">

    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Prefect Server</title>
    <script type="module" crossorigin src="/assets/index-1097d93a.js"></script>
    <link rel="stylesheet" href="/assets/index-c26ac916.css">
  </head>
  <body>
    <div id="app"></div>
    
  </body>
</html>
```

It looked like I might be able to set `PREFECT_UI_SERVE_BASE` from the vite config at https://github.com/PrefectHQ/prefect/blob/bd2bc16cba49b493d09f18fdbe04d8b579e67615/ui/vite.config.ts#L8 to override the serving (see https://github.com/PrefectHQ/prefect/issues/10389 which describes essentially the same issue) -- however, after trying it and looking around at the source a bit, it would seem that value is used at build-time rather than runtime (it's used in the multi-stage build at https://github.com/PrefectHQ/prefect/blob/bd2bc16cba49b493d09f18fdbe04d8b579e67615/Dockerfile#L36). I can confirm that the `index.html` on disk at `/usr/local/lib/python3.10/site-packages/prefect/server/ui` in the container image has static links as well.

Did I miss something? If not, I think this should be a runtime configurable setting to match what the chart allows.

**Comment by jimid27** [comment]
Hello! Thank you for opening this issue.  After talking with the UI team, I have confirmed that the path defined in the `PREFECT_UI_SERVE_BASE` variable is used to inject paths at build time to assets used by the UI code at runtime.  So for this use case, I would recommend rebuilding the UI and referencing the new image in the helm chart.

**Comment by jimid27** [comment]
Great! Yes I think you're correct we should add some more color around this so others don't get tripped up.  Will add these recommendations to our backlog.
