### ISSUE TITLE
Updated Helm Chart for Prefect 2.14.5

### ISSUE THREAD

**Issue by npc2kor** [PrefectHQ/prefect-helm#273]
There's been a new release for Prefect - 2.14.5 - https://github.com/PrefectHQ/prefect/releases/tag/2.14.5 on 16 November, 2023.
However, we are not able to see the changes replicated in the Helm Charts repo. There's been a release - https://github.com/PrefectHQ/prefect-helm/releases/tag/2023.11.16 on the same day (as Prefect 2.14.5 was released), however the helm chart App version still points to 2.14.4. Please find below:

```
C:\Users\USER>helm search repo
NAME                    CHART VERSION   APP VERSION     DESCRIPTION
prefect/prefect-agent   2023.11.16      2.14.4          Prefect Agent application bundle
prefect/prefect-server  2023.11.16      2.14.4          Prefect server application bundle
prefect/prefect-worker  2023.11.16      2.14.4          Prefect Worker application bundle
```

**Comment by jamiezieziula** [comment]
Thanks for letting us know - this has now been released [here](https://github.com/PrefectHQ/prefect-helm/releases/tag/2023.11.20)
