### ISSUE TITLE
Latest release (2023.11.24) uses invalid appVersion

### ISSUE THREAD

**Issue by ashtuchkin** [PrefectHQ/prefect-helm#274]
Hey, we can't use the latest helm chart version because it uses appVersion `v2.14.6`, which leads to using image `prefecthq/prefect:v2.14.6-python3.11-kubernetes`, which does not exist. It looks like the it should be just `2.14.6`.

Seems like the last 2 releases are affected.

**Comment by jimid27** [comment]
Hello! Thank you for reaching out. We have pulled 2023.11.24 with the problematic image.  Please use 2023.11.28 which we have just released to resolve this issue.

**Comment by ashtuchkin** [comment]
Thank you for the quick turnaround! Let me check it works in our environment.

**Comment by ashtuchkin** [comment]
Ok it worked, thank you so much!
