### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by jmeisele** [PrefectHQ/prefect-helm#280]
Do we need to install all 3 helm charts?
The docs say workers are recomended under the agents section

**Comment by jamiezieziula** [comment]
Hi @jmeisele - can you expand a bit more? If you are using Prefect Cloud, you only need to install **either** the `agent` or the `worker` chart. If you are new to Prefect, I would recommend using `workers`. 

If you are attempting to self host Prefect - then you would need to install and manage the `server` chart

**Comment by jmeisele** [comment]
Appreciate the input, this is for self-hosted. So I was trying to understand if all 3 charts were needed or just the server + workers. Appreciate the input 🤝
