### ISSUE TITLE
Add PREFECT_UI_STATIC_DIRECTORY and emptyDir volume mount to fix Permission Error

### ISSUE THREAD

**Issue by marcm-ml** [PrefectHQ/prefect-helm#288]
Is needed to solve bug in prefect mentioned in https://github.com/PrefectHQ/prefect/issues/11640 and solved by prefect 2.14.16

Since image is run as non-root, the chart should provide read/write for the PREFECT_UI_STATIC_DIRECTORY dir. 

Set the env var PREFECT_UI_STATIC_DIRECTORY to the corresponding directory in the chart as well.

Am on mobile right now but will provide more information later if needed

**Comment by parkedwards** [comment]
hey @marcm-ml -- for my understanding + to reproduce, are you setting `podSecurityContext` chart values, specifically `runAsNonRoot: true`?

**Comment by marcm-ml** [comment]
Yes and no, I am using the default chart values but also a version where the securityContext is set but not the podSexurityContext. In both cases, the error persist. AFAIK if you only set the podSecurityContext but not the securityContext (or they have different users), the emptyDir will not have the correct read/writ permissions. So it is important that they match and if podSecurityContext is set, securityContext must be too.
