### ISSUE TITLE
Postgresql pod is still deployed even when setting `postgresql.enabled=false`

### ISSUE THREAD

**Issue by jamiezieziula** [PrefectHQ/prefect-helm#336]
a postgresql pod, etc. is still deployed when "disabling" postgresql. You can reproduce by running

```bash
helm install prefect-server prefect/prefect-server --set postgresql.enabled=false
```

To block postgres from deploying, you would need to also set `postgresql.useSubChart=false`. This is confusing behavior. We should either better document this pattern or change the way in which we control the postgresql implementation

```bash
helm install prefect-server prefect/prefect-server --set postgresql.enabled=false --set postgresql.useSubChart=false
```
 
Relevant slack link [here](https://prefect-community.slack.com/archives/CL09KU1K7/p1717025127801229)

**Comment by mitchnielsen** [comment]
Fair point 👍🏼 

I put up a quick draft in https://github.com/PrefectHQ/prefect-helm/pull/341. Will give it some more thought tomorrow but welcoming feedback anytime.
