### ISSUE TITLE
Support SQLite database

### ISSUE THREAD

**Issue by mitchnielsen** [PrefectHQ/prefect-helm#345]
## Summary

In https://github.com/PrefectHQ/prefect-helm/issues/336, we found that the database configuration was centralized within PostgreSQL - meaning database configuration couldn't be provided outside of the `postgresql` key, which matters if someone wants to use MySQL or even SQLite.

Let's consider providing a new top-level key for configuring the database that's considered if `postgresql.enabled=false`.

## Notes

The [Prefect docs](https://docs-3.prefect.io/3.0rc/manage/self-host) mention: 

> Prefect supports the following databases:
> 1. SQLite (default in Prefect): Recommended for lightweight, single-server deployments. SQLite requires essentially no setup.
> 2. PostgreSQL: Best for connecting to external databases, but requires additional setup (such as Docker). Prefect uses the [pg_trgm](https://www.postgresql.org/docs/current/pgtrgm.html) extension, so it must be installed and enabled.

Elsewhere, it says:

> Use SQLite database for testing only
> SQLite does not support multiprocessing. For high orchestration volume, use PostgreSQL.

So realisticically, most users should be on PostgreSQL. But the documentation shows you how to use SQLite, so I think it's reasonable to support that configuration in the charts. As mentioned in https://github.com/PrefectHQ/prefect-helm/pull/365, users are already using SQLite with the charts with some workarounds.

## Acceptance criteria

- [x] Database configuration can be provided outside of the top-level `postgresql` key if PostgreSQL is not in use.
- [x] SQLite specifically is tested to confirm nothing is hard-coded to work with PostgreSQL

**Comment by mitchnielsen** [comment]
I bet this was indirectly addressed by [https://github.com/PrefectHQ/prefect-helm/pull/365](https://github.com/PrefectHQ/prefect-helm/pull/365/files), but let's try it to be sure and add an SQLite test case to be sure.

**Comment by mitchnielsen** [comment]
@tmyhu - wanted to tag you since you mentioned you were using SQLite. We added direct support for it in https://github.com/PrefectHQ/prefect-helm/releases/tag/2024.12.5195120. If you have any suggestions feel free to create an issue/PR 🤝

**Comment by tmyhu** [comment]
Awesome, that looks great. Thanks for letting me know @mitchnielsen
