### ISSUE TITLE
`existingSecret` config path documentation is wrong

### ISSUE THREAD

**Issue by liqwid** [PrefectHQ/prefect-helm#35]
Documented path is `postgresql.auth.existingSecret`

[Path used in source code](https://github.com/PrefectHQ/prefect-helm/blob/f0e838aa20402fa8c23cb4fca8e6c0576d288b1d/charts/prefect-orion/templates/_helpers.tpl#L136) is `postgresql.existingSecret`

Either doc or sources should be fixed.

Because of that issue, it currently takes a while to figure out why external db authentication does not work.

**Comment by jamiezieziula** [comment]
Thanks @liqwid - I'll take a look today
