### ISSUE TITLE
[Bug] Release 2024.7.15170357 OOM for initcontainer

### ISSUE THREAD

**Issue by marcincuber** [PrefectHQ/prefect-helm#359]
I have hit an OOM issue for initcontainer as we set our limitrange at 128Mi which was too low for the `sync-base-job-template` container.

Setting memory at namespace level to 256Mi resolved the OOM, however, we need support to be able to pass memory,cpu into helmchart for initcontainer. Or you need to set it directly in the deployment spec.

Something like this is missing:
```
          {{- if .Values.initworker.resources }}
          resources: {{- toYaml .Values.initworker.resources | nindent 12 }}
          {{- end }}
```

**Comment by mitchnielsen** [comment]
Thanks for raising this @marcincuber, opened https://github.com/PrefectHQ/prefect-helm/pull/361 to address.
