### ISSUE TITLE
prometheus-prefect-exporter chart have no new releases

### ISSUE THREAD

**Issue by romalukin** [PrefectHQ/prefect-helm#364]
It seems that github actions does not have build and release jobs configured for `prometheus-prefect-exporter` chart. Please release new version. 

Thanks.

**Comment by mitchnielsen** [comment]
Hi @romalukin, we do have the [release workflow for that chart](https://github.com/PrefectHQ/prefect-helm/blob/main/.github/workflows/prometheus-exporter-helm-release.yaml), it's just manual at the moment.

I created a new release, you should be able to see it now:

```
$ helm search repo prefect/prometheus-prefect-exporter -l | head -n 2
NAME                                    CHART VERSION   APP VERSION     DESCRIPTION
prefect/prometheus-prefect-exporter     2024.7.18173342 1.2.0           A Helm chart to deploy Prometheus Prefect Exporter
```
