### ISSUE TITLE
Error configuring base job template

### ISSUE THREAD

**Issue by cchentola** [PrefectHQ/prefect-helm#366]
Configuring base job template with this command ([source](https://github.com/PrefectHQ/prefect-helm/tree/main/charts/prefect-worker#configuring-a-base-job-template-on-the-worker)) is throwing errors in the latest version of prefect-worker:

`helm install prefect-worker prefect/prefect-worker -f values.yaml --set-file worker.config.baseJobTemplate=base-job-template.json`

`Error: INSTALLATION FAILED: values don't meet the specifications of the schema(s) in the following chart(s):
prefect-worker: - worker.config.baseJobTemplate: Invalid type. Expected: object, given: string`

The command works for version 2024.4.4201250

**Comment by parkedwards** [comment]
hey @cchentola - thanks for raising this issue!

Apologies, there was an update to our values schema, where we nested the user-provided baseJobTemplate into an additional `baseJobTemplate.configuration` key after https://github.com/PrefectHQ/prefect-helm/pull/340, but did not update the docs accordingly

I've opened this PR to reflect this change here: https://github.com/PrefectHQ/prefect-helm/pull/368

to move past this, you can update your command line arg like so:

```sh
helm install prefect-worker prefect/prefect-worker -f values.yaml \
  --set-file worker.config.baseJobTemplate.configuration=base-job-template.json
```

**Comment by cchentola** [comment]
Thanks for looking into this!
