### ISSUE TITLE
Add option for creating additional Init Containers for Workers

### ISSUE THREAD

**Issue by NiJuFirenzia** [PrefectHQ/prefect-helm#393]
Currently Workers have an optional Init Container defined for syncing a base job template from a configmap. However, it would be useful to have additional optional init containers for any setup work that a user would want to have completed before the Worker starts up. 

Our team specifically would like to use the init containers to deploy deployments associated with the workers. So when a worker starts, all the necessary deployments will be present in the Prefect UI. 

I will have a PR for this open in the coming days.

**Comment by mitchnielsen** [comment]
Sounds good, thanks @NiJuFirenzia!
