### ISSUE TITLE
ingress.extraHosts not working

### ISSUE THREAD

**Issue by kungtalon** [PrefectHQ/prefect-helm#409]
The error occurs whenever I enable ingress and set the extraHosts like
```
  extraHosts: 
    - name: example.local
      path: /prefect
      pathType: Prefix
```
Error message from helm:
> helm.go:86: 2024-11-10 01:20:27.927320102 -0800 PST m=+0.120036728 [debug] template: prefect-server/templates/ingress.yaml:48:135: executing "prefect-server/templates/ingress.yaml" at <.Values.ingress.servicePort>: nil pointer evaluating interface {}.ingress

By locating the error in the template, it is probably caused by a reference to Values inside a `range` block:
```
{{- range .Values.ingress.extraHosts }}
    - host: {{ .name | quote }}
      http:
        paths:
          - path: {{ default "/" .path }}
            {{- if eq "true" (include "common.ingress.supportsPathType" $) }}
            pathType: {{ default "ImplementationSpecific" .pathType }}
            {{- end }}
            backend: {{- include "common.ingress.backend" (dict "serviceName" (include "common.names.fullname" $) "servicePort" .Values.ingress.servicePort "context" $) | nindent 14 }}
    {{- end }}
```
Changing `.Values.ingress.servicePort` to `$.Values.ingress.servicePort` solves this issue.

**Comment by jamiezieziula** [comment]
Thanks @kungtalon - PR opened with a fix!

**Comment by jamiezieziula** [comment]
@kungtalon - this has been merged and released, available [here](https://github.com/PrefectHQ/prefect-helm/releases/tag/2024.11.14171207)!
