### ISSUE TITLE
persistence should under postgresql.primary

### ISSUE THREAD

**Issue by gq1** [PrefectHQ/prefect-helm#5]
https://github.com/PrefectHQ/prefect-helm/blob/4c5cb68c9d2d88ed38db01529e85e05c666c48d2/charts/prefect-orion/values.yaml#L105

And alos I can't find any usage for postgresql.initdbUser, should be primary.initdb.user?

I checked postgresql helm chart here: https://github.com/bitnami/charts/tree/master/bitnami/postgresql

**Comment by jamiezieziula** [comment]
Thanks @gq1 - reviewing today
