### ISSUE TITLE
PREFECT_API_KEY is required in the agent chart

### ISSUE THREAD

**Issue by john-jam** [PrefectHQ/prefect-helm#53]
In the previous release, it was possible to omit the prefect API secret key configuration: https://github.com/PrefectHQ/prefect-helm/blob/0.6.1/charts/prefect-agent/templates/agent/deployment.yaml#L38

With the new release, it is now mandatory to provide a secret reference and if we want to use the agent only with the deployed orion API, we have to create a fake k8s secret. Any particular reason for that change? I can do a PR if needed.

**Comment by jamiezieziula** [comment]
Ah good point - no, we don't need to require this.
