### ISSUE TITLE
`workQueueName` also needs a value for the agent to run

### ISSUE THREAD

**Issue by padbk** [PrefectHQ/prefect-helm#57]
Kind of related, but `workQueueName` also needs a value for the agent to run, due to the addition of the `-q` variable here https://github.com/PrefectHQ/prefect-helm/blob/8434d5e27ad6a996d7ebb36e9c75e3ee556f65fd/charts/prefect-agent/templates/deployment.yaml#L53

_Originally posted by @padbk in https://github.com/PrefectHQ/prefect-helm/issues/53#issuecomment-1255127774_

**Comment by jamiezieziula** [comment]
Hi @padbk - a workqueue name is required either way.  Before we were defaulting to a value of `prd` but have since removed that.  We can revert to specifying a default value, but either way a name is needed.
