### ISSUE TITLE
Prefect 2.0 UI not working when ingress enabled

### ISSUE THREAD

**Issue by gq1** [PrefectHQ/prefect-helm#6]
Helm installed Prefect 2.0 with postgresql as backend, and ingress enabled with host address  _**prefect.example.com**_

`prefect config set PREFECT_API_URL="http://prefect.example.com/api"`

the flow run states being stored in the database successfully, you can query them in the database table.

But nothing shown in the UI, because all the API calls from the UI page still go to local server: **http://127.0.0.1:4200/api/**

**Comment by gq1** [comment]
adding the following in the values file, kind works, but not perfect.

We limit only one way to access our service.

  env:
    - name: PREFECT_ORION_UI_API_URL
      value: http://***.***.***./api

**Comment by kwmiebach** [comment]
@gq1 I added a docker compose example that works for me in the other issue that you mentioned above.

I was setting PREFECT_ORION_UI_API_URL to the `public` address and port from the `outside`.
And PREFECT_API_URL to a value using an `internal` container/pods address and port. Then
starting orion with  --host 0.0.0.0 
Details see in other issue. It is docker-compose but maybe it helps

**Comment by jamiezieziula** [comment]
@gq1 @kwmiebach can you confirm if you're still facing this issue?

**Comment by jacobdanovitch** [comment]
Has anyone been able to get ingress working with the chart? This fixed the API calls, but I had to use my own ingress as it looks like the chart is setting the servicePort to http/80 instead of 4200 and there doesn't seem to be a way to override this

**Comment by jamiezieziula** [comment]
@jacobdanovitch - this should be fixed with [this](https://github.com/PrefectHQ/prefect-helm/pull/66) pr.  Planning to release this today

**Comment by jacobdanovitch** [comment]
> @jacobdanovitch - this should be fixed with [this](https://github.com/PrefectHQ/prefect-helm/pull/66) pr. Planning to release this today

Just got around to updating today and can confirm everything is working as expected. Thanks!

**Comment by cpatrickalves** [comment]
Hi there, I am also getting Can't connect to Orion API at http://127.0.0.1:4200/api. Check that it's accessible from your machine after the deployment using Helm. 

The UI is available https://prefect.mydomain.com

What value should I set on PREFECT_API_URL?
